### ISSUE TITLE
Use Scratch API to Fetch Comments

### ISSUE THREAD

**Issue by jessiejs** [micahlt/sv2#2]
This uses an HTML scraper, which is a very bad idea, because then, if the site changes, then you have to read it, and it is generally just harder to maintain. I recommend that you use the Scratch API, so that way you can fetch the verification code from the comments in a more stable way.

**Comment by micahlt** [comment]
Nope - this uses the `site-api` from Scratch.  It's what continues to run the comment pages on user and studio pages.  Unfortunately, it does use HTML markup, not JSON.
